name: Deploy to Dev.

on:
  push:
    branches: 
      - dev

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_VERSION: dev-${{github.sha}}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Build docker image
        run: |
          docker build -f Dockerfile -t intervuenext/access-control-module:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Tag docker image
        run: |
          docker tag intervuenext/access-control-module:latest intervuenext/access-control-module:latest
      - name: Push to registry
        run: |
          docker push intervuenext/access-control-module:latest